name = "dc-stonk-bot"
type = "webpack"
zone_id = ""
account_id = "f14896414be741e495df05170840306f"
route = ""
workers_dev = true
compatibility_date = "2021-10-26"
webpack_config = "webpack.config.js"

kv_namespaces = [
    { binding = "CONFIG",id = "a52569585bda46009fd3aae712d177e2" }
]